import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/components/home-page/navbar";
import FooterPage from "@/components/home-page/footer";
import WorkoutProvider from "@/contexts/workoutProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit-Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#000000]`}
    >
      <body className="min-h-full flex flex-col">
        <WorkoutProvider>
          <NavbarPage />

          <div>{children}</div>
          <FooterPage />
          <ToastContainer />
        </WorkoutProvider>
      </body>
    </html>
  );
}
